### ISSUE TITLE
`Create New World` doesn't work when bound to a mouse button

### ISSUE THREAD

**Issue by maskersss** [contariaa/atum#2]
tested left click, right click, mb4; works with `y`
no overlapping hotkeys

**Comment by tildejustin** [comment]
this is likely due to: https://github.com/KingContaria/atum-rewrite/blob/aca85e34c95dc6b4a7153c615b5f57813acf8ecd/src/main/java/me/voidxwalker/autoreset/mixin/hotkey/KeyboardMixin.java#L23
isPressed acts differently to isKeyDown, so I could imagine matchKey is similarly broken. Minecraft does some weird stuff with mouse buttons. Unsure where isPressed is updated in onKey.
